#!/bin/bash

LOG=./log_weekstrong_0202
touch ${LOG}
git log -n 1 >> ${LOG}
#MPI_OPT="--prefix /share/opt/openmpi -x LD_LIBRARY_PATH"

echo "### weak scale, 1proc/node ###" >> ${LOG}
mpirun -n 1 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 27 27 >> ${LOG}
mpirun -n 2 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 28 28 >> ${LOG}
mpirun -n 4 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 29 29 >> ${LOG}
mpirun -n 8 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}

echo "### strong scale, 1proc/node ###" >> ${LOG}
mpirun -n 1 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
mpirun -n 2 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
mpirun -n 4 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
mpirun -n 8 --hostfile hostfile_slot1 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}

echo "### weak scale, 4proc/node ###" >> ${LOG}
mpirun -n 4 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 27 27 >> ${LOG}
mpirun -n 8 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 28 28 >> ${LOG}
mpirun -n 16 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 29 29 >> ${LOG}
mpirun -n 32 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}

echo "### strong scale, 4proc/node ###" >> ${LOG}
mpirun -n 4 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
mpirun -n 8 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
mpirun -n 16 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
mpirun -n 32 --hostfile hostfile_slot4 ${MPI_OPT} ./job.sh 30 30 >> ${LOG}
