#!/bin/bash
if [ $# -lt 1 ] ; then
        cat << EOF >&2
        usage: $0 GATE
           GATE: RX, RZ, H, RU, CNOT or SWAP
EOF
    exit 1
fi

GATE=$1

MyName=`basename "$0"`
Time=`date "+%y%m%d%H%M%S"`
HostName=`hostname | awk -F . '{ print $1; }'`
#LOG="./log/$MyName.$GATE.$Time.$HostName."`printf "%06x" $$`
LOG="./log/$MyName.$GATE.$HostName.$Time"
touch ${LOG}
echo "### mpi-qulacs version ###" >> ${LOG}
git log -n 1 >> ${LOG}

CMD="job.sh qulacs-gate.py -g ${GATE}"
HOSTFILE="hostfile"
OPTMPI="-x UCX_IB_MLX5_DEVX=no"
#TEST="echo"
TEST=

echo "### weak scale, 1proc/node ###" >> ${LOG}
ppn=1
baseqc=30
for i in {0..6}; do
	${TEST} mpirun -n $((ppn*2**i)) --npernode $ppn --hostfile ${HOSTFILE} ${OPTMPI} ${CMD} -n $((baseqc+i)) >> ${LOG}
done

baseqc=32
echo "### strong scale, 1proc/node ###" >> ${LOG}
for i in {2..6}; do
	${TEST} mpirun -n $((ppn*2**i)) --npernode $ppn --hostfile ${HOSTFILE} ${OPTMPI} ${CMD} -n ${baseqc} >> ${LOG}
done

echo "### weak scale, 4proc/node ###" >> ${LOG}
ppn=4
baseqc=30
for i in {0..6}; do
	${TEST} mpirun -n $((ppn*2**i)) --npernode $ppn --hostfile ${HOSTFILE} ${OPTMPI} ${CMD} -n $((baseqc+i)) >> ${LOG}
done

baseqc=32
echo "### strong scale, 4proc/node ###" >> ${LOG}
for i in {2..6}; do
	${TEST} mpirun -n $((ppn*2**i)) --npernode $ppn --hostfile ${HOSTFILE} ${OPTMPI} ${CMD} -n ${baseqc} >> ${LOG}
done

