#!/bin/bash

LOG=./log_hbench_0225.txt
touch ${LOG}
echo "### mpi-qulacs version ###" >> ${LOG}
git log -n 1 >> ${LOG}
MPI_OPT="-x UCX_IB_MLX5_DEVX=no"
CMD="./job.sh hbench.py -d 11 -r 5"
#CMD="./job.sh qvolume.py -d 10 -r 5"
#TEST=echo 
TEST=

echo "### weak scale, 1proc/node(max 34qubit/64node) ###" >> ${LOG}
ppn=1
for i in {0..6}; do
	${TEST} mpirun -n $((2**i)) --npernode $ppn --hostfile hostfile ${MPI_OPT} ${CMD} -n $((30+i)) >> ${LOG}
done

echo "### strong scale, 1proc/node ###" >> ${LOG}
for i in {4..6}; do
	${TEST} mpirun -n $((2**i)) --npernode $ppn --hostfile hostfile ${MPI_OPT} ${CMD} -n 34 >> ${LOG}
done

echo "### weak scale, 4proc/node(max 34qubit/64node) ###" >> ${LOG}
ppn=4
for i in {0..6}; do
	${TEST} mpirun -n $((4*2**i)) --npernode $ppn --hostfile hostfile ${MPI_OPT} ${CMD} -n $((30+i)) >> ${LOG}
done

echo "### strong scale, 4proc/node ###" >> ${LOG}
for i in {4..6}; do
	${TEST} mpirun -n $((4*2**i)) --npernode $ppn --hostfile hostfile ${MPI_OPT} ${CMD} -n 34 >> ${LOG}
done

echo "### 64 node scale, 1proc/node ###" >> ${LOG}
ppn=1
for i in {18..36}; do
	${TEST} mpirun -n 64 --npernode $ppn --hostfile hostfile ${MPI_OPT} ${CMD} -n $i >> ${LOG}
done

echo "### 64 node scale, 4proc/node ###" >> ${LOG}
ppn=4
for i in {24..36}; do
	${TEST} mpirun -n 256 --npernode $ppn --hostfile hostfile ${MPI_OPT} ${CMD} -n $i >> ${LOG}
done
