#!/bin/bash

LOG=./log_weakstrong_0207py
touch ${LOG}
echo "### mpi-qulacs version ###" >> ${LOG}
git log -n 1 >> ${LOG}

echo "### weak scale, 1proc/node ###" >> ${LOG}
ppn=1
for i in {0..6}; do
	echo mpirun -n $((2**i)) --npernode $ppn --hostfile hostfile -x UCX_IB_MLX5_DEVX=no ./job.sh -n $((27+i)) >> ${LOG}
done

echo "### strong scale, 1proc/node ###" >> ${LOG}
for i in {0..6}; do
	echo mpirun -n $((2**i)) --npernode $ppn --hostfile hostfile -x UCX_IB_MLX5_DEVX=no ./job.sh -n 30 >> ${LOG}
done

echo "### weak scale, 4proc/node ###" >> ${LOG}
ppn=4
for i in {0..6}; do
	echo mpirun -n $((4*2**i)) --npernode $ppn --hostfile hostfile -x UCX_IB_MLX5_DEVX=no ./job.sh -n $((27+i)) >> ${LOG}
done

echo "### strong scale, 4proc/node ###" >> ${LOG}
for i in {0..6}; do
	echo mpirun -n $((4*2**i)) --npernode $ppn --hostfile hostfile -x UCX_IB_MLX5_DEVX=no ./job.sh -n 30 >> ${LOG}
done
